server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    gzip on;
    gzip_min_length 256;
    gzip_types text/plain text/css application/javascript image/svg+xml;

    location ~* \.(png|svg|jpe?g|gif|ico|css|js)$ { expires 30d; add_header Cache-Control "public"; }

    location / {
        try_files $uri $uri/ =404;
    }
}
